<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'zDbSession\Module'                              => __DIR__ . '/Module.php',
  'zDbSession\Entity\Session'                      => __DIR__ . '/src/zDbSession/Entity/Session.php',
  'zDbSession\Session\SaveHandler\DoctrineGateway' => __DIR__ . '/src/zDbSession/Session/SaveHandler/DoctrineGateway.php',
);
